server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qlnv?useSSL=false&serverTimezone=UTC
    username: Trong
    password: 31122003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
